name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Match your Node.js version
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.email "cfortiz1@jhu.edu"
        git config --global user.name "cristina-irene-fortiz"
    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions token
      run: |
        npx gh-pages -d build --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cristina-irene-fortiz/celebrity_haters.git
