name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Ensure this matches your project's Node.js version
        cache: 'npm' # Caches npm dependencies to speed up builds

    - name: Install Dependencies
      run: npm ci # 'npm ci' ensures a clean and reproducible install

    - name: Build Project
      env:
        NODE_OPTIONS: --openssl-legacy-provider # Your package.json includes this
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.email "cfortiz1@jhu.edu"
        git config --global user.name "Cristina Irene Fortiz"

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
      run: npm run deploy
